version: '3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    restart: unless-stopped

  dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piro_dash
    volumes:
      - .:/home/dev/piro
    command: python3.7 web/app.py
    ports:
      - "8080:8080" # For Dash
    networks:
      - backend

networks:
  backend:
    name: mongo-net
